#!/bin/bash

# Script para sincronizar otimizações com o sistema na nuvem AWS
echo "🚀 SINCRONIZANDO OTIMIZAÇÕES COM A NUVEM"
echo "=" * 50

echo "📋 Arquivos modificados:"
echo "• config/settings.json - Valores de entrada otimizados"
echo "• bots/executor.py - Stop loss dinâmico implementado"
echo "• .env - Configurações de proteção ajustadas"
echo ""

echo "💡 Para aplicar as mudanças no sistema da nuvem (AWS EC2):"
echo "1. Conecte-se ao EC2 via EC2 Instance Connect"
echo "2. Navegue até o diretório: cd /home/ubuntu/R7_V3_Deploy"
echo "3. Execute os comandos:"
echo ""
echo "   # Parar o sistema atual"
echo "   pkill -f python"
echo ""
echo "   # Atualizar configurações"
echo "   cp /home/ubuntu/R7_V3_Deploy/config/settings.json config/settings.json.backup"
echo "   cat > config/settings.json << 'EOF'"
echo "{"
echo "  \"banca_referencia_usdt\": 2355.05,"
echo "  \"entrada_usd\": 35.0,"
echo "  \"valor_minimo_posicao_usd\": 1.0,"
echo "  \"config_geral\": {"
echo "    \"exposicao_maxima_usdt\": 350.0,"
echo "    \"meta_diaria_total_usdt\": 50.0,"
echo "    \"tp_pct\": 1.5,"
echo "    \"sl_pct\": 0.8,"
echo "    \"symbols_monitorados\": ["
echo "      \"BTCUSDT\", \"ETHUSDT\", \"SOLUSDT\", \"BNBUSDT\", \"ADAUSDT\","
echo "      \"XRPUSDT\", \"DOTUSDT\", \"LINKUSDT\", \"AVAXUSDT\", \"POLUSDT\","
echo "      \"LTCUSDT\", \"NEARUSDT\", \"ATOMUSDT\", \"FETUSDT\", \"RENDERUSDT\","
echo "      \"PEPEUSDT\", \"WIFUSDT\", \"DOGEUSDT\", \"ZECUSDT\", \"ARBUSDT\","
echo "      \"MAGICUSDT\", \"JUPUSDT\""
echo "    ]"
echo "  }"
echo "}"
echo "EOF"
echo ""
echo "   # Atualizar variáveis de ambiente"
echo "   sed -i 's/R7_SAFE_MARGIN_PCT=.*/R7_SAFE_MARGIN_PCT=0.5/' .env"
echo "   sed -i 's/R7_MAX_HOLD_HOURS=.*/R7_MAX_HOLD_HOURS=36/' .env"
echo "   sed -i 's/R7_QUICK_PROFIT_PCT=.*/R7_QUICK_PROFIT_PCT=2.5/' .env"
echo ""
echo "   # Reiniciar o sistema"
echo "   nohup python main.py > logs/system.log 2>&1 &"
echo ""
echo "⚠️  IMPORTANTE: O executor.py com stop loss dinâmico precisa ser"
echo "    copiado manualmente ou através de deploy completo."
echo ""
echo "🎯 BENEFÍCIOS APLICADOS:"
echo "• Entradas 3.5x maiores ($35 vs $10)"
echo "• Stop loss inteligente por tipo de moeda"
echo "• Menos conservadorismo, mais oportunidades"
echo "• Proteções mantidas contra grandes perdas"